const API_URL = `/messages`

const GET_MESSAGES = 'GET_MESSAGES'
const NEW_MESSAGE = 'NEW_MESSAGE'
const EDIT_MESSAGE = 'EDIT_MESSAGE'
const DELETE_MESSAGE = 'DELETE_MESSAGE'

export { API_URL, GET_MESSAGES, NEW_MESSAGE, EDIT_MESSAGE, DELETE_MESSAGE }
