const API_URL = `/messages`

const API_ERROR = 'ERROR'

const GET_MESSAGES = 'GET_MESSAGES'
const NEW_MESSAGE = 'NEW_MESSAGE'
const EDIT_MESSAGE = 'EDIT_MESSAGE'
const DELETE_MESSAGE = 'DELETE_MESSAGE'
const BEGIN_EDIT_MESSAGE = 'BEGIN_EDIT_MESSAGE'

export {
  API_URL, API_ERROR, GET_MESSAGES, NEW_MESSAGE,
  EDIT_MESSAGE, DELETE_MESSAGE, BEGIN_EDIT_MESSAGE
}
